image:
  name: gscloudsolutions/devops-mate:7.154.0
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD

pipelines:
  pull-requests:
      feature/*: #any branch with a feature prefix
        - step:
            name: Scratch Org Deployment Validation
            script:
              - echo 'Create Scratch Org'
              - sfOrgs createOrg -x 'CIOrg-$BITBUCKET_BUILD_NUMBER' -p ./config/scratch-def.json -t $DEVHUB_ORG_TYPE -u $DEVHUB_USERNAME -s $DEVHUB_PASSWORD
              - echo 'Create a full deployment artifact/package'
              - sfPackages source-combined -f true -v $MAJOR_VERSION.$MINOR_VERSION.$PATCH.$BITBUCKET_BUILD_NUMBER -p $BITBUCKET_CLONE_DIR -n $LATEST_COMMIT_HASH_TAG || if test $? -eq 21; then exit 0; else exit 1; fi
              - echo 'Deploy the package to Scratch Org'
              - sfDeploy mdapipackage -l $TEST_LEVEL -p $BITBUCKET_CLONE_DIR -a 'CIOrg-$BITBUCKET_BUILD_NUMBER' -v $MAJOR_VERSION.$MINOR_VERSION.$PATCH.$BITBUCKET_BUILD_NUMBER
              - sfOrgs deleteOrg -t $DEVHUB_ORG_TYPE -u $DEVHUB_USERNAME -s $DEVHUB_PASSWORD -a 'CIOrg-$BITBUCKET_BUILD_NUMBER'

  branches:
    # Pipeline for master branch
    'master':
      #A step to facilitate manual step
      - step:
          name: Package is ready for versioning
          script:
            - echo 'Package is ready for versioning to release the new changes'
      #Unlocked Package Version Creation
      - step:
          name: Create Package Version
          trigger: manual
          script:
            - echo 'Create Package Version'
            - sfPackages second-gen-version -c $MIN_OVERALL_CODE_COVERAGE -d sfdx-source -x true -v $DEVHUB_USERNAME -s $DEVHUB_PASSWORD --workingDirectory $BITBUCKET_CLONE_DIR -t $BITBUCKET_COMMIT #-n $MAJOR_VERSION.$MINOR_VERSION.$PATCH.$BITBUCKET_BUILD_NUMBER
            - cat sfdx-project.json
            - git add sfdx-project.json
            - git commit -m 'Updating the sfdx-project.json with the latest version'
            - git push
